name: netmon_sumkal
version: 1.0.0+1
publish_to: none
description: Netmon Sumkal.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.3.6
  http: ^0.13.3
  intl: ^0.17.0
  firebase_core: ^1.3.0
  cloud_firestore: ^2.4.0
  shared_preferences: ^2.0.6
  font_awesome_flutter: ^9.1.0
  lottie: ^1.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  lints: 1.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/pln.json
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
